/* Apple TV Remote Driver for Windows XP
 * Copyright (C) Sylas Hollander. All Rights Reserved.
 * Based on atvclient by Christoph Cantillon and Peter Korsgaard
 * SPDX-License-Identifier: GPL-2.0-only
 */

#pragma once

/**
 * Specify every conceivable button that could be on a remote.
 * As more remotes are supported, this enum will grow.
 */

typedef enum
{
	REMOTE_BUTTON_APPLE_MENU,
	REMOTE_BUTTON_APPLE_PLAY_PAUSE,
	REMOTE_BUTTON_APPLE_FAST_FWD,
	REMOTE_BUTTON_APPLE_REWIND,
	REMOTE_BUTTON_APPLE_VOLUME_UP,
	REMOTE_BUTTON_APPLE_VOLUME_DOWN,
	REMOTE_BUTTON_APPLE_ALUMINUM_SELECT,

	REMOTE_BUTTON_0,
	REMOTE_BUTTON_1,
	REMOTE_BUTTON_2,
	REMOTE_BUTTON_3,
	REMOTE_BUTTON_4,
	REMOTE_BUTTON_5,
	REMOTE_BUTTON_6,
	REMOTE_BUTTON_7,
	REMOTE_BUTON_8,
	REMOTE_BUTON_9,
	REMOTE_BUTTON_A,
	REMOTE_BUTTON_B,
	REMOTE_BUTTON_C,
	REMOTE_BUTTON_D,
	REMOTE_BUTTON_E,
	REMOTE_BUTTON_F,

	REMOTE_BUTTON_UP,
	REMOTE_BUTTON_DOWN,
	REMOTE_BUTTON_LEFT,
	REMOTE_BUTTON_RIGHT,
	REMOTE_BUTTON_SELECT,
	REMOTE_BUTTON_RETURN,

	REMOTE_BUTTON_PLAY,
	REMOTE_BUTTON_PAUSE,
	REMOTE_BUTTON_STOP,
	REMOTE_BUTTON_SKIP,
	REMOTE_BUTTON_REPLAY,
	REMOTE_BUTTON_REWIND,
	REMOTE_BUTTON_FAST_FW,
	REMOTE_BUTTON_RECORD,
	REMOTE_BUTTON_VOL_UP,
	REMOTE_BUTTON_VOL_DOWN,
	REMOTE_BUTTON_MUTE,
	REMOTE_BUTTON_CHANNEL_UP,
	REMOTE_BUTTON_CHANNEL_DN,
	REMOTE_BUTTON_PREV_CH,

	REMOTE_BUTTON_POWER,
	REMOTE_BUTTON_MENU,
	REMOTE_BUTTON_SOURCE,
	REMOTE_BUTTON_SETUP,
	REMOTE_BUTTON_GUIDE,
	REMOTE_BUTTON_HOME,
	REMOTE_BUTTON_INFO,
	REMOTE_BUTTON_MY_TV,
	REMOTE_BUTTON_QUEUE,
	REMOTE_BUTTON_SLEEP,
	REMOTE_BUTTON_EXIT,
	REMOTE_BUTTON_MUSIC,
	REMOTE_BUTTON_MOVIES,
	REMOTE_BUTTON_PICTURES,
	REMOTE_BUTTON_HELP,

	REMOTE_BUTTON_F1,
	REMOTE_BUTTON_F2,
	REMOTE_BUTTON_F3,
	REMOTE_BUTTON_F4,
	REMOTE_BUTTON_F5,
	REMOTE_BUTTON_F6,
	REMOTE_BUTTON_F7,
	REMOTE_BUTTON_F8,
	REMOTE_BUTTON_F9,
	REMOTE_BUTTON_F10,
	REMOTE_BUTTON_F11,
	REMOTE_BUTTON_F12,
	REMOTE_BUTTON_F13,
	REMOTE_BUTTON_F14,

	REMOTE_BUTTON_RED,
	REMOTE_BUTTON_ORANGE,
	REMOTE_BUTTON_YELLOW,
	REMOTE_BUTTON_GREEN,
	REMOTE_BUTTON_BLUE,
	REMOTE_BUTTON_PURPLE,
	REMOTE_BUTTON_PINK,
	REMOTE_BUTTON_BLACK,
	REMOTE_BUTTON_WHITE,

	REMOTE_BUTTON_MAX,
	REMOTE_BUTTON_INVALID = 0xFF
} remote_button;

typedef struct {
	remote_button 	button; // Intermediate button format
	uint8_t     	modifiers; // Modifiers
	uint8_t 		key_code; // Virtual key_code code for SendKey
	const char*		name;
} key_map;

boolean press_key(remote_button button);
boolean release_key(void);
void setup_keymap(void);